---
title: "writing_function"
author: "Yineng Chen"
date: "2019/10/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

## get started

```{r}
x = rnorm(30,4,2.3)
x_again = rnorm(30,6,.3)


(x - mean(x))/sd(x)
```

```{r}
z_score = function(x){
  
   if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  (x - mean(x))/sd(x)
  
}
```

```{r, error=TRUE}
z_score(x= x_again)
z_score(x = "123")
```


## multiple outputs
```{r}
mean_and_sd = function(input_x){
   if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
 tibble( 
   mean_input = mean(input_x),
    sd_input = sd(input_x)      
         ) 
}
```

```{r}
mean_and_sd(x)
```

```{r}
mean_and_sd = function(input_x){
   if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
 list( 
   mean_input = mean(input_x),
    sd_input = sd(input_x),
   z_score = (input_x - mean(input_x))/sd(input_x)
         ) 
}
```

## multiple inputs

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```


```{r}
sim_regression = function(n, beta0 =2 , beta1 = 3){
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

```{r}
sim_regression(30,3,4)
```


```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_review = function(url){
  
  review_titles = dynamite_html %>%
   html_nodes("#cm_cr-review_list .review-title") %>%
   html_text()

  review_stars = dynamite_html %>%
   html_nodes("#cm_cr-review_list .review-rating") %>%
   html_text()

  review_text = dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text()

 reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
 )
  
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)
```

